### ISSUE TITLE
Slider Dragging Boolean public

### ISSUE THREAD

**Issue by Jacobwasbeast** [CottonMC/LibGui#100]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to deviate from the main branch or remake the Abstract Slider and Slider class because the dragging boolean for sliders is not public instead it is protected.

**Describe the solution you'd like**

Changing the boolean for dragging from protected to public inside Abstract Slider class.

**Describe alternatives you've considered**

Keeping it the same and just make users remake a copy of the Abstract Slider and Slider class with changes included.

**Additional context**
![image](https://user-images.githubusercontent.com/38381609/109375808-39c30e00-7885-11eb-840a-ec06e7c6de94.png)

**Comment by Juuxel** [comment]
What exactly do you need it for? It's meant for the slider implementations (mostly just visuals), and it should only ever *need* to be accessed from subclasses of `WAbstractSlider`. I can add a getter for it if it's needed though (no setter because it's meant to be controlled by the widget).

**Comment by Jacobwasbeast** [comment]
I would personally use it as like a cool drag effect more cosmetics or something around that kind of logic. It really has no purpose besides that as I can think of.
