### ISSUE TITLE
Opening GUI from command twice crashes game

### ISSUE THREAD

**Issue by lougehrig10** [CottonMC/LibGui#106]
**Describe the bug**
When using a command to open a GUI, running the command, hitting escape, and running the command again causes the game to crash

**To Reproduce**
1. Create a CottonClientScreen and LightweightGuiDescription
2. Register a command that when executed opens the screen.
3. In Minecraft, run the command to open the screen
4. Hit escape to exit the screen
5. Run the command to open the screen again
6. Experience crash

**Expected behavior**
No crash and for the screen to reappear

**Version of the (please complete the following information):**
 - Mod: 3.3.5
 - Fabric API: 0.30.0
 - Minecraft: 1.16.5

**Comment by Juuxel** [comment]
Please post the full game log in a Gist or on another paste site from when the crash happens.

**Comment by lougehrig10** [comment]
[Crash Report](https://gist.github.com/lougehrig10/431b1aad1951240deb558a74eb6d4d5c)

**Comment by Juuxel** [comment]
Do you use a server-side (regular) command or a client-side command for opening the screen?

**Comment by lougehrig10** [comment]
I believe client side. I register the command inside the onInitializeClient function with the CommandRegistrationCallback.EVENT.register function

**Comment by Juuxel** [comment]
No, you cannot use that for opening `LightweightGuiDescription`s. `CommandRegistrationCallback` is only for server-side commands that are handled on the server thread. Your commands are server-side commands that are only registered in client *environments* (note the difference between the logical client side/thread and client distributions/environments), which means they are singleplayer-only server commands.

`LightweightGuiDescription`s and `MinecraftClient.openScreen` are *client-only* and can't be used from server-side commands or other server code. In this case, you're experiencing a threading issue as `openScreen` doesn't work properly when called from the server thread and causes various bugs such as this crash.

In this case, you should move the command to be a proper client-side command using Fabric API's `ClientCommandManager`, which runs commands on the client thread which does work properly for opening screen. (Another option would be `SyncedGuiDescription` and `ServerPlayerEntity.openHandledScreen` if you want a screen that's controlled by the server, such as a container block screen.)

**Comment by lougehrig10** [comment]
Oh, ok! Thanks for the help! However, registering the command with ClientCommandManager.DISPATCHER will allow the command to show up and run code, but calling MinecraftClient.getInstance().openScreen() does not render a screen. Anything else I am doing wrong?

**Comment by lougehrig10** [comment]
context seems to be a `CommandContext<FabricClientCommandSource>` but it doesn't have `getClient()`. I tried `context.getSource().getClient()`, but it still does not render the GUI

**Comment by Juuxel** [comment]
Are there any exceptions in the game log?

**Comment by lougehrig10** [comment]
No Exceptions. I also placed a `out.println()` just to make sure the command is running (which it is), but no error or GUI from `ctx.getSource().getClient().openScreen(new MyScreen(new MyGUI()))`

**Comment by lougehrig10** [comment]
If it helps, `ctx.getSource().getClient().currentScreen` gets updated to the proper screen, but the GUI just doesn't render and the game acts normally

**Comment by Juuxel** [comment]
Hmm, what does your `GuiDescription` class look like?

**Comment by lougehrig10** [comment]
[GuiDescription Class](https://gist.github.com/lougehrig10/50539a3e0b5e028562b7ec3f54911943)

**Comment by Juuxel** [comment]
That looks normal to me - I'm not really sure why your screen isn't working. Could you also post your screen class (if you're not using `CottonClientScreen` directly), as well as the opening command?

**Comment by lougehrig10** [comment]
[This should be everything](https://gist.github.com/lougehrig10/e8ce49c7d45fde85cbad7b90d81a8991)

Thanks for still helping out!

**Comment by lougehrig10** [comment]
Ah! I think I found the problem. Commands are run from the `ChatScreen` class. Under `keyPressed` it seems that when enter is pressed, it calls `this.sendMessage(string)` and then later `this.client.openScreen((Screen)null)` which tells the client to 'open' to the game.

I believe what is happening is that the command is being run, the game opens the screen, and then immediately closes the screen because of the chat screen trying to close. To test this theory, my command creates a new `Timer` that runs openScreen 1 second later, allowing the chat screen to close and then open my screen

**Comment by Juuxel** [comment]
Ah yeah, this makes sense. To fix this, try wrapping the `openScreen` call in a `getClient().execute(() -> {<code here>})` call which should postpone it to be later in the game's execution.

**Comment by lougehrig10** [comment]
Sadly, just `getClient().execute(() -> {client.openScreen(new Screen())})` does not delay the execution long enough, there still needs to be a delay somewhere. Although I guess you could put a loop checking the state of the screen and wait until the current screen is the game screen before opening the desired screen

**Comment by Juuxel** [comment]
It should be possible to actually post the screen opening as a task to the game's task queue (`getClient().getTaskQueue()` iirc, but I can't check right now) which could also work for delaying. (I haven't tried this, though)

**Comment by Juuxel** [comment]
@lougehrig10 A late-ish update: you can use `getClient().send(...)` instead of `execute` to delay it. (I actually needed this for LibGui's test mod 😄)

**Comment by Juuxel** [comment]
Closing this because you don't seem to have any more problems. Feel free to open a new issue if you need help :rocket:
