### ISSUE TITLE
[21w19a] WTabPanel renders incorrectly

### ISSUE THREAD

**Issue by Rover656** [CottonMC/LibGui#108]
**Describe the bug**
When using a WTabPanel in 21w19a, the panel background and widgets render in the bottom right of the screen, rather than in the middle.

**To Reproduce**
1. Create a GUI with a WTabPanel as the root panel.
2. Give it a couple of tabs
3. View the GUI in game, the rendering is completely off.

**Screenshots**
![image](https://user-images.githubusercontent.com/20544390/118508395-13479d00-b727-11eb-8063-336f1b8e97c8.png)

**Versions:**
 - Mod: 4.0.0-alpha.1+21w11a
 - Fabric API: 0.34.4+1.17
 - Minecraft: 21w19a

**Comment by Juuxel** [comment]
Should be fixed in da554fce. (`ItemIcon` didn't properly reset the translations it did)
