### ISSUE TITLE
problem with WItemSlot inside WScrollPanel

### ISSUE THREAD

**Issue by tksonix** [CottonMC/LibGui#112]
I don't know if I'm doing it correctly or not and I'm new to modding so please bear with me :)

I tried to make a long inventory which can be scrolled vertically, so I did this:
```
WGridPanel root = new WGridPanel();
setRootPanel(root);
root.setSize(23 * 18, 12 * 18);

root.add(this.createPlayerInventoryPanel(), 0, 7);

WItemSlot wItemSlot = WItemSlot.of(blockInventory, 0, 12, 30);
WScrollPanel scrollPanel = new WScrollPanel(wItemSlot);
root.add(scrollPanel, 10, 0, 13, 12);

root.validate(this);
```
And the GUI looked like this, no scroll bar:
![Screen Shot 2021-06-01 at 5 27 52 PM](https://user-images.githubusercontent.com/25430053/120360619-d96abf00-c300-11eb-8b50-e5bbd94bddac.png)

Then I tried to place the WItemSlot inside a WPlainPanel then inside WScrollPanel:
```
WItemSlot wItemSlot = WItemSlot.of(blockInventory, 0, 12, 30);
WPlainPanel plainPanel = new WPlainPanel();
plainPanel.add(wItemSlot, 0, 0);
WScrollPanel scrollPanel = new WScrollPanel(plainPanel);
root.add(scrollPanel, 10, 0, 13, 12);
```
Now the scroll bar is there, but actual item slots are still going outside panel, while the background is correctly hidden away. Also they didn't align, when I tried to scroll, the background moves correctly but actual item slot don't move:
![Screen Shot 2021-06-01 at 5 29 25 PM](https://user-images.githubusercontent.com/25430053/120361401-b260bd00-c301-11eb-8b2d-94e00501986e.png)

**Version of the (please complete the following information):**
 - Mod 3.4.0
 - Fabric API 0.34.2
 - Minecraft 1.16.5

**Comment by Juuxel** [comment]
Item slots are backed by vanilla `Slot` instances, which are limited as they're not fully LibGui widgets. They can't be moved around the same way nor partially hidden (which is done in scroll panels), so their use in `WScrollPanel`s and `WListPanel`s is unsupported.

If you want a scrollable list of slots, you can implement one like vanilla does with its creative inventory, or like some mods do (I think Expanded Storage has it, for example). Sadly, I don't have any LibGui example to show you.

**Comment by tksonix** [comment]
Ok I see the problem. Thanks fotr the reply.
