### ISSUE TITLE
ValidatedSlot#setVisible crashes on 1.17

### ISSUE THREAD

**Issue by GabrielOlvH** [CottonMC/LibGui#113]
**Describe the bug**
ValidatedSlot#setVisible crashes on 1.17
https://hastebin.com/yudowopara.apache

**To Reproduce**
Create a tab panel with slots and try to switch tabs

MC 1.17-pre4
LibGUI 4.0.0-beta.3

**Additional context**
Mixin doesn't check if a field is final before creating an acessor setter, Java 8 did not care but Java 16 does. I am not 100% sure how to bypass that but you can simply override Slot#isEnabled to effectively hide it without having to change its position

**Comment by Pyrofab** [comment]
A simple solution I found is to create a mixin with just an unused `@Shadow @Mutable @Final boolean visible` field. That will remove the final modifier, fixing the accessor.
