### ISSUE TITLE
Cant open screen

### ISSUE THREAD

**Issue by vladimirmin** [CottonMC/LibGui#118]
this line `MinecraftClient.getInstance().openScreen(new Screen(new ModGui()));` runs when the command is typed in chat, but nothing happens(but when screen is opened via use of item everything works)

**Comment by Juuxel** [comment]
Are you using client-side commands? In that case, you need to wrap the `openScreen` call in a `client.send` call:

https://github.com/CottonMC/LibGui/blob/2e037343d27a2c8ae8aee022249d1023c1c91479/GuiTest/src/main/java/io/github/cottonmc/test/client/LibGuiTestClient.java#L36-L40

(Side note: If you're opening it from an item, a block or server-side/normal command, you need to use screen handlers/`SyncedGuiDescription`, which will fix your issue)

**Comment by shikukuya** [comment]
fixed my same issue, thanks :)
