### ISSUE TITLE
Game crashes when Screen is opened after any key or mouse movement is pressed.

### ISSUE THREAD

**Issue by hayasaka-13** [CottonMC/LibGui#124]
**Rendering Issue**
Getting the error of:
_java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (io.github.cottonmc.cotton.gui.client.CottonClientScreen) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by the screen not calling super.init(Lnet/minecraft/client/MinecraftClient;II)V_
whenever I try to open a client-side screen through an Item.

Actual crash report can be found here:
https://pastebin.com/0QUWjHuh

**Comment by Juuxel** [comment]
This is an issue with Pipbud, not LibGui.
