### ISSUE TITLE
The current screen (net.minecraft.client.gui.screen.Screen) has not been correctly initialised

### ISSUE THREAD

**Issue by shadowradience** [CottonMC/LibGui#127]
Launching the game, it will open the screen once upon use of the item to open the client screen, then never again in that project.   You have to create a new project to get it to pop up once. This error occurs on fabric 1.17.1 using the fabric-example-mod repository.

1. Create Screen extending CottonClientScreen
2. Create Description extending LightweightGuiDescription(I just put the data from the libgui wiki for the description)
        WGridPanel root = new WGridPanel();
        setRootPanel(root);
        root.setSize(256, 240);
        root.setInsets(Insets.ROOT_PANEL);
        
        WSprite icon = new WSprite(new Identifier("minecraft:textures/item/redstone.png"));
        root.add(icon, 0, 2, 1, 1);
        
        WButton button = new WButton(new TranslatableText("gui.examplemod.examplebutton"));
        root.add(button, 0, 3, 4, 1);
        
        WLabel label = new WLabel(new LiteralText("Test"), 0xFFFFFF);
        root.add(label, 0, 4, 2, 1);
    
        root.validate(this); 
3. Create a basic item then override use
4. Add MinecraftClient.getInstance().setScreen(new Screen(new Description()));
5. Launch game
6. Right click item

As far as I'm aware, it should open a screen that has an icon of redstone with a button underneath everytime i right click.  However it rarely does.

Crash Log:
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 8/2/21, 12:46 AM
Description: Ticking screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (net.minecraft.client.gui.screen.Screen) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by the screen not calling super.init(Lnet/minecraft/client/MinecraftClient;II)V
	at net.minecraft.client.gui.screen.Screen.ensureEventsAreInitialised(Screen.java:1350)
	at net.minecraft.client.gui.screen.Screen.fabric_getBeforeTickEvent(Screen.java:1363)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeTick(ScreenEvents.java:150)
	at net.minecraft.client.MinecraftClient.handler$zcd000$beforeScreenTick(MinecraftClient.java:4147)
	at net.minecraft.client.MinecraftClient.method_1572(MinecraftClient.java:1767)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:507)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1767)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1132)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:746)
	at net.minecraft.client.main.Main.main(Main.java:191)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.ensureEventsAreInitialised(Screen.java:1350)
	at net.minecraft.client.gui.screen.Screen.fabric_getBeforeTickEvent(Screen.java:1363)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeTick(ScreenEvents.java:150)
	at net.minecraft.client.MinecraftClient.handler$zcd000$beforeScreenTick(MinecraftClient.java:4147)
	at net.minecraft.client.MinecraftClient.method_1572(MinecraftClient.java:1767)

-- Affected screen --
Details:
	Screen name: io.github.cottonmc.cotton.gui.client.CottonClientScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:507)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Player983'/196, l='ClientLevel', x=-226.50, y=75.00, z=213.50]]
	Chunk stats: 841, 489
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,73,208), Section: (at 0,9,0 in -14,4,13; chunk contains blocks -224,0,208 to -209,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 349 game time, 349 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:365)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2432)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:763)
	at net.minecraft.client.main.Main.main(Main.java:191)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1059391392 bytes (1010 MiB) / 1749024768 bytes (1668 MiB) up to 2107637760 bytes (2010 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8681
	Graphics card #1 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1c8f
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6663
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14879.23
	Virtual memory used (MB): 13092.86
	Swap memory total (MB): 6840.08
	Swap memory used (MB): 1096.33
	JVM Flags: 4 total; -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=localhost:53668,server=n,suspend=y -XX:+ShowCodeDetailsInExceptionMessages
	Fabric Mods: 
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		libgui: LibGui 4.1.5+1.17.1
		libninepatch: LibNinePatch 1.1.0
		minecraft: Minecraft 1.17.1
		minesandmobs: Example Mod ${version}
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 630 GL version 3.2.0 - Build 27.20.100.8681, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Player Count: 1 / 8; [ServerPlayerEntity['Player983'/196, l='ServerLevel[New World]', x=-226.50, y=75.00, z=213.50]]
	Data Packs: vanilla, Fabric Mods

**Comment by Juuxel** [comment]
This is caused by a threading issue. You **cannot** open screens with `MinecraftClient.setScroon` from `Item.use` or any other common-sided code as it will either cause threading issues or a straight up crash.

You need to make your screen either use `SyncedGuiDescription` and screen handlers, or a custom S2C opening packet.

**Comment by ButterKing-28** [comment]
Hello, I have the same error. would you be able to send a link to a video or explain how to use the "SyncedGuiDescription and screen handlers, or a custom S2C opening packet" please? I am very new to coding.
