### ISSUE TITLE
How to Edit Parts of Gui (Textures Only, not a modder)

### ISSUE THREAD

**Issue by sweetsosweet** [CottonMC/LibGui#128]
**Describe the bug**

I don't think this is a bug, but I'm wondering if there's a way to adjust colours for some parts of the gui? For context I'm not a modder, so I'm not doing any coding just adjusting textures for a resource pack, but I can't find a place to adjust the section pictured below. Just want to make sure if there's a texture I'm missing somewhere:

**To Reproduce**
Just editing assets ---> textures

**Screenshots** *Optional*
![libgui](https://user-images.githubusercontent.com/15041593/128620629-ac038ee0-caf1-4ec8-a1ca-48c6e94c8515.png)

**Version of the (please complete the following information):**
 - Using Plant In A Jar mod 2.2.2, not sure which version of libgui
 - Fabric API 0.37.1
 - Minecraft 1.17.1

**Comment by Juuxel** [comment]
Hmm, I'm not familiar with Plant In A Jar, but it most likely draws the slots using code instead of textures so that might not be changeable.

I'll fix this hardcoding for most LibGui-using mods by creating texture files for slots, but no ETA for that yet.

**Comment by sweetsosweet** [comment]
Thank you, that does make sense! And no rush, I thought it might be coding based (was just crossing fingers I might have missed something). 

-cheers!

**Comment by CodeF53** [comment]
@Juuxel 
> I'll fix this hardcoding for most LibGui-using mods by creating texture files for slots, but no ETA for that yet.

could you please consider making slots not hardcoded?
Its super hard to get around this as a resource pack dev. I have considered making a companion mod that mixins into LibGUI to fix this.

letting us customize backgrounds but not slots feels pretty nonsensical.

Desired look:
![image](https://user-images.githubusercontent.com/37855219/188773844-0742fbda-02e4-4879-a521-e893366ea986.png)

VS best I can do with libGUI inventories
![image](https://user-images.githubusercontent.com/37855219/188773903-597249cc-df45-46e8-9233-958b7ebcb5e0.png)

**Comment by Juuxel** [comment]
@CodeF53 Sorry, I've completely forgotten about this issue. It's not intentional - most LibGui widgets drew themselves using code, especially originally, but I've slowly been refactoring them to use textures in updates. I'll make an update for slots very soon™
