### ISSUE TITLE
Using WLabel or WText in a HUD crashes the game

### ISSUE THREAD

**Issue by boop-the-dog** [CottonMC/LibGui#130]
**Describe the bug**
When using a WLabel or WText in a HUD, it spams the logs with errors containing "(ScreenDrawing) Rendering text hover effects outside of a screen!"

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to render a WLabel or WText in a HUD
2. Crash

**Expected behaviour** *Optional*
No crash occurs when using WLabel or WText and Hover Effects not being rendered

**Screenshots** *Optional*
<img width="593" alt="Screenshot 2021-08-09 174528" src="https://user-images.githubusercontent.com/62707056/128778567-0ccae047-e11a-48e3-9785-72a6033e53de.png">
<img width="1857" alt="Screenshot 2021-08-09 174843" src="https://user-images.githubusercontent.com/62707056/128778918-976b1870-b501-4573-a1c7-1710664aa4d4.png">
java.lang.ClassCastException: class net.minecraft.client.gui.screen.ChatScreen cannot be cast to class io.github.cottonmc.cotton.gui.impl.client.CottonScreenImpl (net.minecraft.client.gui.screen.ChatScreen and io.github.cottonmc.cotton.gui.impl.client.CottonScreenImpl are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @68746f22)

**Version of the (please complete the following information):**
 - Fabric API - 0.11.3
 - Minecraft - 1.17.1

**Comment by Juuxel** [comment]
Thanks for the report - the original code was really dumb. Fixed in LibGui 4.1.6+1.17.1.
