### ISSUE TITLE
UI issue when using with the Dark enchanting mod

### ISSUE THREAD

**Issue by Eddie-Carrizales** [CottonMC/LibGui#132]
**Describe the bug**
Hi, there is an issue when using this mod with the Dark Enchanting mod, where the UI is all messed up when trying to use the enchanting table from the mod. 

**To Reproduce**
1. Create the dark enchanting table from the mod
2. click on the enchanting table and try to enchant an item
3. as you will see, the UI will be placed behind the item inventory and wont allow you to see what enchantment you want to choose

**Expected behavior** *Optional*
for the enchantments to be shown above the item inventory UI not behind it where its not supposed to be. 

**Version of the (please complete the following information):**
-I am on a Mac laptop, this might also be important to note
 - Dark enchanting mod (this happens with all versions Ive tried, but im currently on 1.17.1)
 - Fabric API 1.17.1 
 - Minecraft 1.17.1

**Additional context** *Optional*
Its a really simple issue really, all that has to be done is to move the enchantments above the inventory UI where they can be seen and used by the user :)

**Comment by Boundarybreaker** [comment]
Ah, yes, Macs and rendering. Couple things to look through:
- Have you reported this to Dark Enchanting? This could be a bug with how it sets up its screens and not with LibGui itself.
- This doesn't seem like it could be a scaled-resolution issue, but try adding in [RetiNO](https://www.curseforge.com/minecraft/mc-mods/retino) to see if that helps things.

**Comment by Eddie-Carrizales** [comment]
The creator of Dark enchanting mod did respond back to me saying that it was due to how LibGui handles it. But I'll try RetiNO and see if that fixes it. Thanks tho

**Comment by Juuxel** [comment]
I don't know the specifics of that mod so I can't really help here. I wouldn't exactly be surprised if it's related to #114, and RetiNO could fix it too (it probably has something to do with retina's scaled resolutions).

**Comment by Eddie-Carrizales** [comment]
Hey using RetiNO fixed the issue!!! Thank you so much!!

**Comment by Juuxel** [comment]
This should be fixed in the latest LibGui which doesn't use raw window dimensions anymore - working with macOS's cursed "retina".
