### ISSUE TITLE
BackgroundPainter.createColorful() should accept long values

### ISSUE THREAD

**Issue by boop-the-dog** [CottonMC/LibGui#138]
**Describe the solution you'd like**
Allow `BackgroundPainter.createColorful()` to accept long values instead of integers because `0xFFFFFFFF` (color code w/ alpha for full white and full opacity) is larger than the max integer limit

**Comment by Juuxel** [comment]
`0xFF_FFFFFF` is in fact a fully valid int. (Not in Kotlin though, if you're using it, since it involves a sign change. You can "trick" kotlinc by doing `(0xFF shl 24) or 0xFFFFFF`)
