### ISSUE TITLE
[bug?/inconsistency?] SyncedGuiDescription::onSlotClick does not call Inventory::removeStack for QUICK_MOVE

### ISSUE THREAD

**Issue by supersaiyansubtlety** [CottonMC/LibGui#146]
**Describe the bug**
The `removeStack` (both methods) logic of my inventory is respected when my `SyncedGuiDescription` receives a non-shift-click, but not a shift-click. 

I looked into it a bit and it looks like for `QUICK_MOVE`s `SyncedGuiDescription` sets stack counts, and for everything else delegates to `super`, which calls `Inventory::removeStack` in the case of `PICKUP` (non-shift-click).

This has come up for my mod because I have an inventory that holds 'ghost items', items that aren't taken when inserted and aren't given when removed, behaves as expected for `PICKUP` but not `QUICK_MOVE` (you can easily dupe items by putting them in and then shift-clicking them out).

**To Reproduce**
1) Create an inventory and override its `removeStack` methods and add some custom behavior
2) create a `SyncedGuiDescription` for that inventory and a way for players to open the gui
3) try both clicking and shift-clicking in the gui to remove items from the inventory
4) notice inconsistent behavior

**Expected behavior**
I would expect both clicking and shift-clicking to respect inventories' logic for removing stacks.

**Versions**
 - LibGui 5.1.0+1.18
 - FAPI 0.44.0+1.18
 - MC 1.18.1

**Comment by Juuxel** [comment]
This is actually not done by vanilla either, and doing it is very annoying with the way quick move code is structured (in both vanilla and LibGui). If you want to prevent picking up those items altogether, you can disable the extracting/inserting on those slots with `setModifiable`/`setTakingAllowed`/`setInsertingAllowed`.

**Comment by supersaiyansubtlety** [comment]
Ah, so it's due to the vanilla inventory limitations, ok. Thanks for explaining. 

`setModifiable`/`setTakingAllowed`/`setInsertingAllowed` aren't quite what I need, so I just overrode the click method and gave it custom behavior for `QUICK_MOVE`
