### ISSUE TITLE
Question on how to close GUI

### ISSUE THREAD

**Issue by Stefano-De-Cesare** [CottonMC/LibGui#151]
I made a small GUI that allows the player to choose its race, kinda like origins.
When the player picks it's race, the screen is supposed to close, how can i do this?
Here's an example of what i want to do:
![image](https://user-images.githubusercontent.com/65348662/150463116-5a510a8e-6024-463d-80ae-8b29e7148f75.png)
which is inside the constructor of this class:
![image](https://user-images.githubusercontent.com/65348662/150463208-4b72882e-c95b-4c2d-80c2-9c571071d28e.png)
i don't knows if i should do it this way, but so far its been working out :v

P.S: i'm relatively new to minecraft modding 
P.S.S: i'm using fabric for 1.18.1

**Comment by Juuxel** [comment]
You can close the gui with `MinecraftClient.getInstance().setScreen(null)`.

**Comment by ButterKing-28** [comment]
> You can close the gui with `MinecraftClient.getInstance().setScreen(null)`.

When I do this on 1.19.4 It crashes the game even when I run "MinecraftClient.getInstance().setScreen(null)". I tried to put it an if statement saying if its world.isClient but the issue the World would return as Null and crash it anyways. I have no idea how to fix it.
