### ISSUE TITLE
When creating a mod in 1.18.2 the 1.18 version throws errors on :runClient

### ISSUE THREAD

**Issue by Gregory1234** [CottonMC/LibGui#156]
**Describe the bug**
When using the 1.18 version of the library on 1.18.2, when running `:runClient` errors are thrown such as:
`Mixin apply for mod fabric-structure-api-v1 failed fabric-structure-api-v1.mixins.json:StructureFeatureAccessor -> net.minecraft.world.gen.feature.StructureFeature: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching field_24861:Ljava/util/List; in net/minecraft/world/gen/feature/StructureFeature for fabric-structure-api-v1.mixins.json:StructureFeatureAccessor->@Accessor[FIELD_SETTER]::setSurfaceAdjustingStructures(Ljava/util/List;)V [INJECT Applicator Phase -> fabric-structure-api-v1.mixins.json:StructureFeatureAccessor -> Apply Accessors ->  -> Locate -> fabric-structure-api-v1.mixins.json:StructureFeatureAccessor->@Accessor[FIELD_SETTER]::setSurfaceAdjustingStructures(Ljava/util/List;)V]`

**How to fix it**
The errors are caused by additional unneeded dependencies on removed fabric-api modules(fabric-structure-api-v1 and fabric-tag-extensions-v0). The pull request I made(#155) fixed them by updating the fabric-api dependency, so even though there are no real code changes it would be good to make a release. To prevent this from happening in the future, there should be explicit dependency on specific fabric api modules, instead of depending on the whole thing.

**To Reproduce**
1. Create a 1.18.2 mod and declare a dependency on LibGui
2. Try to execute `:runClient`

**Version of the (please complete the following information):**
 - Mod 5.3.1+1.18
 - Fabric API 0.48.0
 - Minecraft 1.18.2

**Comment by Juuxel** [comment]
Ah, I see. I'll make a new release but for now you can just exclude the broken Fabric API modules via Gradle.

**Comment by Gregory1234** [comment]
The thing is I tried but I don't think its possible because LibGui states that it depends on the whole fabric-api, and if it doesn't find those 2 modules at runtime it complains.

**Comment by Juuxel** [comment]
The dependencies have been fixed in 5.3.2.
