### ISSUE TITLE
Crash from NoSuchMethodError: BufferBuilder.vertex on 19w39a+

### ISSUE THREAD

**Issue by franiscoder** [CottonMC/LibGui#16]
**Describe the bug**
There is a crash with LibGUI with 19w40a. I wanted to create a GitHub issue instead of just saying it on discord to be less disruptive, yet hopefully, you will check this. The crash happens because of rendering changes, again. 

**To Reproduce**
1. Try to open a libgui GUI in 19w39a or above- it won't work and you will crash.

**Expected behavior** *Optional*
It doesn't crash while rendering the screen.

**Version of the (please complete the following information):**
 - Personal Mod, in Development Environment
 - Fabric API
 - Minecraft

**Comment by Boundarybreaker** [comment]
Can you provide a crash log so we know what part of rendering broke?

**Comment by franiscoder** [comment]
Here's a 19w39a crash report, IDK if it would be different in 40a but it shouldn't since it was just like 20 bug fixes and one unrelated thing to this. 
https://pastebin.com/J9Zv9ttb

**Comment by Boundarybreaker** [comment]
ahh, they thanos'd BufferBuilder.

**Comment by franiscoder** [comment]
closing since it is fixed
