### ISSUE TITLE
[Question] Is there a way to add a background for HUD text?

### ISSUE THREAD

**Issue by alex3236** [CottonMC/LibGui#160]
I wonna do something like this:
![图片](https://user-images.githubusercontent.com/45303195/166458308-f5226f2e-51a1-48a4-ae26-7b21c13df9c4.png)
But I can't find a way to add background for label or HUD easily.

**Comment by Juuxel** [comment]
Backgrounds like that can be drawn by using `ScreenDrawing.coloredRect` or vanilla's `DrawableHelper.fill` with a translucent colour (so in `0xAA_RRGGBB`, `AA` is something else than `FF`) in the HUD render event.

Additionally, if you use vanilla's `TextRenderer` directly for drawing the string (as you might want to do in a HUD), you can use it to get the width and height needed for the background rectangle.

**Comment by alex3236** [comment]
Looks good! btw, is there any way to modify the scale of elements?

**Comment by Juuxel** [comment]
Not directly, no, but in most cases you can use the matrix stack to scale the rendering as usual. (So you can for example wrap a `super.paint` call with a `matrices.push(); matrices.scale(); super.paint(); matrices.pop();` chain.) The only thing this doesn't work with is item rendering which uses its own matrix stack for some reason.

**Comment by alex3236** [comment]
Got it, thanks for your help :)
