### ISSUE TITLE
Autowrapping Labels

### ISSUE THREAD

**Issue by 1ndiigo** [CottonMC/LibGui#165]
**Is your feature request related to a problem? Please describe.**
WLabels do not wrap properly, which makes long strings of text go off of the screen

**Describe the solution you'd like**
I have seen #158 and I don't know if a solution would be feasible, but if it is simple to implement I would like to see this added

**Describe alternatives you've considered**
If there already is a solution to this issue (maybe a widget I missed) tell me.

**Comment by Juuxel** [comment]
WLabel is a simple single line widget by design. For multiple lines you can use WText, which has more features.
