### ISSUE TITLE
Config GUI for Mod Menu? (Still no info on wiki)

### ISSUE THREAD

**Issue by SyberiaK** [CottonMC/LibGui#167]
**Is your feature request related to a problem? Please describe.**
I'm interested in using config GUI made by LibGui in Mod Menu but it seems like there's still no information about that on wiki.
![изображение](https://user-images.githubusercontent.com/97897772/176957472-0b261e58-dbbb-4cd4-af9c-393c2fa5e21b.png)

**Describe the solution you'd like**
Update this wiki page I guess...

**Comment by Juuxel** [comment]
You do it the same way as any other Mod Menu config screen, you can follow their instructions and use `CottonClientScreen` as the screen.

**Comment by SyberiaK** [comment]
Ah, yes, figured it out like a minute ago 😅

**Comment by SyberiaK** [comment]
Oh, by the way, is there any way to place a widget on relative cords? Like `0.5, 0.5` for the center of screen

**Comment by Juuxel** [comment]
Sorry for the late response (it seems my notifications aren't working properly), but you can use `Window.getScaledWidth/getScaledHeight` to get the width/height of the game window, then position the widgets accordingly.

(Please open a new issue in the future for new questions if possible)
