### ISSUE TITLE
Cannot use BackgroundPainter on server.

### ISSUE THREAD

**Issue by luke-devs** [CottonMC/LibGui#176]
**Describe the bug**
When using .setBackgroundPainter(BackgroundPainter.VANILLA); on a server (multiplayer not singleplayer) the server crashes with an error log.

**To Reproduce**
Use  .setBackgroundPainter(BackgroundPainter.VANILLA) on a multiplayer server.

**Expected behavior** *Optional*
I should be able to open my GUI, I have a WPlainPanel which I am trying to set the background painter of, this works in singleplayer.

**Screenshots** *Optional*

**Version of the (please complete the following information):**

 - Mod
  modImplementation include("io.github.cottonmc:LibGui:6.3.0+1.19")
  
 - Fabric API
 1.19.2
 
 - Minecraft
1.19.2
 

**Additional context** *Optional*

Here is the crash log:

13.11 14:15:58 [Server] Server thread/ERROR Encountered an unexpected exception
13.11 14:15:58 [Server] INFO java.lang.ExceptionInInitializerError: null
13.11 14:15:58 [Server] INFO at settlerstavern.shrines.WeatherShrineGUI.<init>(WeatherShrineGUI.java:42) ~[tavern_shrines-1.0.jar:?]
13.11 14:15:58 [Server] INFO at settlerstavern.shrines.block.GuiBlockEntity.createMenu(GuiBlockEntity.java:52) ~[tavern_shrines-1.0.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_3222.method_17355(class_3222.java:1040) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at settlerstavern.shrines.block.GuiBlock.method_9534(GuiBlock.java:24) ~[tavern_shrines-1.0.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_3225.method_14262(class_3225.java:338) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_3244.method_12046(class_3244.java:1145) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
13.11 14:15:58 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
13.11 14:15:58 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class io.github.cottonmc.cotton.gui.client.NinePatchBackgroundPainter in environment type SERVER
13.11 14:15:58 [Server] INFO at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.10.jar:?]
13.11 14:15:58 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454) ~[fabric-loader-0.14.10.jar:?]
13.11 14:15:58 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407) ~[fabric-loader-0.14.10.jar:?]
13.11 14:15:58 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
13.11 14:15:58 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
13.11 14:15:58 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
13.11 14:15:58 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
13.11 14:15:58 [Server] INFO at io.github.cottonmc.cotton.gui.client.BackgroundPainter.createNinePatch(BackgroundPainter.java:141) ~[libgui-6.3.0+1.19-dd0312291a77e0c6.jar:?]
13.11 14:15:58 [Server] INFO at io.github.cottonmc.cotton.gui.client.BackgroundPainter.createNinePatch(BackgroundPainter.java:123) ~[libgui-6.3.0+1.19-dd0312291a77e0c6.jar:?]
13.11 14:15:58 [Server] INFO at io.github.cottonmc.cotton.gui.client.BackgroundPainter.<clinit>(BackgroundPainter.java:41) ~[libgui-6.3.0+1.19-dd0312291a77e0c6.jar:?]
13.11 14:15:58 [Server] INFO ... 23 more

The line it is referring to (42) is this:
WPlainPanel requirementsHeader = new WPlainPanel();
requirementsHeader.setBackgroundPainter(BackgroundPainter.VANILLA);

**Comment by Juuxel** [comment]
This is intended. `BackgroundPainter` is a client-only class so you can only use it in code annotated with `@Environment(CLIENT)`, for example `GuiDescription.addPainters`.
