### ISSUE TITLE
[ResourcePack] - Assets ? -  How can i change the Scroll Bar in our Resource Pack

### ISSUE THREAD

**Issue by SpigotDE** [CottonMC/LibGui#177]
Hey there, i wanna change the scroll bar in the mod LevelZ.
It uses your Libgui textures, but i cant find the scroll bar asset. 

Could you tell me where i can find it pls

**Comment by Juuxel** [comment]
Scroll bars/`WScrollBar`s aren't currently rendered using textures, so they can't be modified using resource packs.

**Comment by SpigotDE** [comment]
Ah damn, thx
