### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by MrMelon54** [CottonMC/LibGui#178]
**Describe the bug**
I'm a fellow mod dev trying to update my mod to 1.19.3.
Here is a bug report: https://mclo.gs/dqG11ir

**To Reproduce**
1. Game just crashes on launch

**Version of the (please complete the following information):**
 - [Multiple Server Lists](https://modrinth.com/mod/multiple-server-lists) (dev 1.19.3 version) - my mod
 - LibGUI 6.3.0-1.19 as library
 - Fabric API 0.68.1+1.19.3
 - Minecraft 1.19.3

**Comment by Juuxel** [comment]
Based on the log, it looks like jankson-fabric is broken and needs updating first (libgui uses it).

**Comment by MrMelon54** [comment]
Looks like jankson has a fix, but you probably already know that.

**Comment by Juuxel** [comment]
Well, I'm the one who fixed it lol

**Comment by Juuxel** [comment]
Released as 6.5.0.

**Comment by MrMelon54** [comment]
awesome
