### ISSUE TITLE
Support Forge

### ISSUE THREAD

**Issue by dmkenza** [CottonMC/LibGui#180]
LibGui has been using only Network module from Fabric.

You can also support Forge.

I reworked LibGui for Forge with Architectury API. 
https://github.com/dmkenza/LibGui_universal

I'm using Forge LibGui in my mod
https://github.com/dmkenza/DiscHolder_universal

I will be glad if you will support Forge version offically also.

**Comment by Juuxel** [comment]
I'm not planning to support Forge.
