### ISSUE TITLE
Selecting text in a WTextField applies blue tint to wrong field.

### ISSUE THREAD

**Issue by BlazingTwist** [CottonMC/LibGui#182]
**Describe the bug**
If a Panel contains mutliple TextFields, selecting text in one TextField will apply a blue tint to the next rendered TextField.

**To Reproduce**
Gui Description:
```java
public class ExampleGui extends LightweightGuiDescription {
	public ExampleGui() {
		WPlainPanel panel = new WPlainPanel();
		panel.setSize(100, 55);

		WTextField field1 = new WTextField();
		panel.add(field1, 5, 5, 90, 20);

		WTextField field2 = new WTextField();
		panel.add(field2, 5, 30, 90, 20);

		panel.validate(this);
		setRootPanel(panel);
	}
}
```

Write text into field1, select the text, observe field2 turning blue.
![Screenshot_8](https://user-images.githubusercontent.com/39350649/216179791-b22d6ef4-23db-4cb8-bfee-5e34743737b8.png)

**Expected behavior**
The second TextField should not turn blue.
Optionally, I would expect the first TextField to turn blue.

**Versions:**
 - LibGui:6.5.1+1.19.3
 - fabric-api:0.68.1+1.19.3
 - Minecraft 1.19.3

**Comment by BlazingTwist** [comment]
Note: I'm pretty sure the fix is as simple as adding
```java
RenderSystem.setShaderColor(0.0F, 0.0F, 1.0F, 1.0F);
```
to the end of `WTextField.invertedRect()`

**Comment by Juuxel** [comment]
Thanks for the report! The fix did indeed work. I also considered just making `ScreenDrawing.coloredRect` reset the shader colour, but someone might have a use for it I guess?
