### ISSUE TITLE
Hover  Text for WButtons

### ISSUE THREAD

**Issue by ButterKing-28** [CottonMC/LibGui#188]
**Is your feature request related to a problem? Please describe.**
This is just a feature request! I am making a GUI for fun and on the WGridPanel there is one button that is a 1x1 and only has an image of an item on it (I wanted it that way). But now my users don't know what it does (which could be fun but sometimes I would like it if they did).

**Describe the solution you'd like**
Maybe somehow have a way to add a small text box that would pop up near the cursor when you hover over it (and maybe have it have a set customizable length (in seconds (float)) it takes before it pops up so it doesn't get in the way). This can be added as a separate type of button or just a thing that you can add to WButtons

**Describe alternatives you've considered**
Or just don't. It's just an idea! : )

**Comment by Juuxel** [comment]
This is a feature that exists already.  You can add tooltips to any widget, such as buttons, like this:
```java
var button = new WButton(new ItemIcon(Items.DIAMOND_SWORD)) {
    @Environment(EnvType.CLIENT)
    @Override
    public void addTooltip(TooltipBuilder tooltip) {
        tooltip.add(Text.translatable("my.tooltip.translation.key"));
    }
};
```

**Comment by ButterKing-28** [comment]
Thanks!! : )
