### ISSUE TITLE
Conflicts with owo-lib

### ISSUE THREAD

**Issue by TheCatRiX** [CottonMC/LibGui#193]
**Describe the bug**
Crashes when owo-lib is installed

**To Reproduce**
1. Install owo-lib
2. Try to launch
3. See error

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/58901923/230153584-de0a8db9-fc24-4a63-9459-a8356f02c815.png)

**Logs**
https://mclo.gs/nuDv0uK

**Versions:**
 - LibGui 7.0.0 Beta 1 (Beta 2 has this issue too)
 - owo-lib 0.10.3
 - Quilted Fabric API 6.0.0 Beta 2
 - Quilt Loader 0.18.6 (1.19.4)

**Comment by Juuxel** [comment]
This is not caused by LibGui; owo-lib appears to be incompatible with Fabric's API for shaders. (LibGui just uses Fabric API for registering its own shader.)
