### ISSUE TITLE
onSlotUpdate (listener) for WItemSlot

### ISSUE THREAD

**Issue by frqnny** [CottonMC/LibGui#20]
WItemSlot needs a way to say if it was used, therefore I recommend something like WButton's onClick. Maybe so field that gets passed to ValidatedSlot and ran when setStack and takeStack are, which I think are the ones that handle that stuff. 

I also want to say that I would like to do this PR myself but I just want a thumbs up from your part to make sure you're okay with it or whether you prefer doing something else.

**Comment by franiscoder** [comment]
or it could be named onSlotUpdate

**Comment by falseresync** [comment]
I don’t see a problem. Wait for an approval from more people

**Comment by frqnny** [comment]
I think this was already done.
