### ISSUE TITLE
Allow creation of buttons that aren't 20 pixels high

### ISSUE THREAD

**Issue by MarcusElg** [CottonMC/LibGui#204]
**Is your feature request related to a problem? Please describe.**
Currently buttons are forced to be 20 pixels high but can have any width. This is quite frustrating as it doesn't allow for the creation of small buttons. Personally I would use it for small + and - buttons for increase/decreasing a value in the gui.

**Describe the solution you'd like**
Remove the hardcoded value (when breaking changes can be done). Until then maybe it could be a seperate widget? Or some sort of extra setting that forces a specific height.

**Comment by Juuxel** [comment]
This was added in 9.0.0.
