### ISSUE TITLE
Tooltips Don't Work

### ISSUE THREAD

**Issue by Anxietie** [CottonMC/LibGui#210]
**Describe the bug**
Tooltips added to buttons don't show up in game when the button is hovered over in the gui.

**To Reproduce**
1. Create a gui
2. Create a WButton
3. Add a tooltip to the WButton

**Screenshots** *Optional*
![2023-08-23_19 43 47](https://github.com/CottonMC/LibGui/assets/84636109/939af67a-2122-4939-8524-aa7b1276ba16)

**Version of the (please complete the following information):**
 - LibGui v8.0.2
 - Fabric API v0.87.0
 - Minecraft 1.20.1

**Additional context** *Optional*
Code used to reproduce:
```java
public class TestScreen extends CottonClientScreen {
    public TestScreen(GuiDescription description) {
        super(description);
    }
}
```

```java
public class TestGui extends LightweightGuiDescription {
    public TestGui() {
        WGridPanel root = (WGridPanel) rootPanel;

        WButton button = new WButton(Text.literal("test"));
        button.addTooltip(new TooltipBuilder().add(Text.literal("this is just a test")));

        root.add(button, 0, 0);
        root.validate(this);
    }
}
```

```java
while (KeybindRegister.TEST_KEY.wasPressed()) {
    if (client.currentScreen == null)
        client.send(() -> client.setScreen(new TestScreen(new TestGui())));
}
```

**Comment by Juuxel** [comment]
This is not how tooltips work. The *widget* is responsible for adding the tooltip lines in `addTooltip`, while LibGui calls that method - consider it mostly override-only from a user's POV. This is how tooltips generally work in Minecraft, including block and item tooltips.

The correct way to add tooltips is to override that method:

```java
new WButton(Text.literal("test")) {
    @Override
    public void addTooltip(TooltipBuilder builder) {
        // add the lines
    }
}
```
