### ISSUE TITLE
[wiki] misspell ClientCottonScreen -> CottonClientScreen

### ISSUE THREAD

**Issue by voidpointer0x00** [CottonMC/LibGui#215]
_«[Subclassing ClientCottonScreen](https://github.com/CottonMC/LibGui/wiki/Client-Sided-Guis#subclassing-clientcottonscreen)»_ should be «Subclassing CottonClientScreen»
```md
# Subclassing ClientCottonScreen
...
public class ExampleScreen extends CottonClientScreen {
```
![image](https://github.com/CottonMC/LibGui/assets/43143315/22cccf97-116c-4c09-a687-b59215e0c5e1)

**Comment by Juuxel** [comment]
Thanks for the report, fixed.
