### ISSUE TITLE
Some if statements aren't using pattern matching instanceof

### ISSUE THREAD

**Issue by VeryWeirdUser** [CottonMC/LibGui#216]
It's not a big problem but there are many **if** statements that cast object "manually" when checking if the object is an instance of something. For example: 
```java
if (child instanceof WPanel) ((WPanel) child).layout();
```
could be changed to
```java
if (child instanceof WPanel panel) panel.layout();
```

(sorry if my english is silly asf)

**Comment by Juuxel** [comment]
Good spot, these are all from before the Java feature was added (to Minecraft's codebase at least).
