### ISSUE TITLE
Can't Figure Out How To Add Widgets To Tab GUIs

### ISSUE THREAD

**Issue by fragger57** [CottonMC/LibGui#219]
This is what I have so far : 

        setRootPanel(root);

        root.add(new WWidget(), builder -> {
            builder.icon(new TextureIcon(LOGO));
            builder.tooltip(Text.literal("Creator Overlays"));
        });

        root.add(new WWidget(), builder -> {
            builder.icon(new TextureIcon(TOGGLE_ON));
            builder.tooltip(Text.literal("Rule of Thirds"));
        });

        root.add(new WWidget(), builder -> {
            builder.icon(new TextureIcon(TOGGLE_OFF));
            builder.tooltip(Text.literal("Golden Ratio"));
        });

All it does is create a Tab Panel with three tabs, but I can't figure out how to add widgets and stuff to the tab GUIs, like Buttons, Toggles, Text, etc. When the root panel is a Tab Panel, all root.add() let's you do is add more tabs, so I'm assuming it has something to do with the tab builder?

Also note that I don't have all the textures created for the tab icons yet, so I'm just using whatever textures I have for testing purposes.

**Comment by Juuxel** [comment]
The widget parameter of `WTabPanel.add` represents the contents of the tab.

In the snippet, you're passing `new WWidget()` to `add`, which means you're adding tabs with no content. You can replace the empty widget with e.g. a panel of your choice where you can add the widgets you want.

**Comment by fragger57** [comment]
Ok that makes sense. Thanks for you're help!
