### ISSUE TITLE
Can't figure out how to paint a background

### ISSUE THREAD

**Issue by legoraft** [CottonMC/LibGui#220]
I'm trying to make an advancement-like screen for a mod, but I can't figure out how to paint the background of my panel. I've tried `setBackgroundPainter` combined with `addPainters()` and `getBackgroundPainter`, but I still don't get any form of painted background.

I'm currently using this code to add to my gui:
```java
public class QuestLineGui extends LightweightGuiDescription {

    public QuestLineGui() {
        WGridPanel root = new WGridPanel();
        setRootPanel(root);
        root.setSize(252, 140);
        root.setInsets(Insets.ROOT_PANEL);

        root.setBackgroundPainter(BackgroundPainter.createNinePatch(new Identifier("minecraft:textures/block/dirt.png")));
        root.getBackgroundPainter().paintBackground(new MatrixStack(), 0, 0, root);

        root.validate(this);
    }

}
```

This is just called through a quick hotkey and `client.setScreen(new CottonClientScreen(new QuestLineGui()));`

**Comment by Juuxel** [comment]
1. Background painters should be set in the `addPainters` method of your GUI description. Since your code sets the background painter in the constructor, it gets replaced by that method.

```java
@Override
public void addPainters() {
    getRootPanel().setBackgroundPainter(...);
}
```

2. `paintBackground` and all other `paint*` methods aren't meant to be called independently with freshly created matrix stacks etc. If you set the background painter in `addPainters`, its `paintBackground` method will be called automatically with the correct parameters.

**Comment by legoraft** [comment]
I got it to work, but would there be a way to make that advancement panel 'style' panel, because I want to draw the background with some sort of inset within the panel

**Comment by Juuxel** [comment]
Yeah, you can for example make a custom background painter that first draws the dirt background and then the shadow on top.

**Comment by legoraft** [comment]
I still have a question: How would I go about drawing  on certain sections of the background, so I can draw the shadow only in certain spots?

**Comment by Juuxel** [comment]
That's more of a general rendering question. For example, if you want a shadow along your panel's inner edge, you can use a nine-slice sprite with the shadow and draw it the size of the panel.

**Comment by legoraft** [comment]
Okay, I just have some issues that the backgroundpainter just paints the full panel every time. I want to have a few sections, but I can't really find one

**Comment by Juuxel** [comment]
All stock background painters in LibGui are designed to draw the full bounding rectangle of the widget.

If you want a smaller region, you can draw those using more general draw methods (like the ones in `ScreenDrawing` and `DrawContext`). You can also use those calls inside a custom background painter if needed.

**Comment by legoraft** [comment]
I've found out how to make my own widgets with the following code:
```java
@Environment(EnvType.CLIENT)
    @Override
    public void paint(DrawContext context, int x, int y, int width, int height) {
        ScreenDrawing.texturedGuiRect(context, x, y, width, height, new Identifier("minecraft:texture/block/dirt.png"), 0xFFFFFFFF);
    }
```

but when I call it, I don't know how I can find out how to get the drawontext

**Comment by LopyMine** [comment]
If you need a DrawContext you can implements the BackgroundPainter interface and draw what you want:
```Java
        BackgroundPainter backgroundPainter = ((context, left, top, panel) -> {
            //context means DrawContext
            //left means x
            //top means y
            //panel means your root panel or your widget
            ScreenDrawing.texturedGuiRect(context, left, top, panel.getWidth(), panel.getHeight(), new Identifier("minecraft:texture/block/dirt.png"), 0xFFFFFFFF);
        });
```
There is another way to implements BackgroundPainter, there is no difference

```Java
        BackgroundPainter backgroundPainter = new BackgroundPainter() {
            @Override
            public void paintBackground(DrawContext context, int left, int top, WWidget panel) {
                //context means DrawContext
                //left means x
                //top means y
                //panel means your root panel or your widget
                ScreenDrawing.texturedGuiRect(context, left, top, panel.getWidth(), panel.getHeight(), new Identifier("minecraft:texture/block/dirt.png"), 0xFFFFFFFF);
            }
        };
```

**Comment by Juuxel** [comment]
I'd also note that `paint` methods aren't meant to be called directly (only in other `paint` methods), LibGui will provide the required `DrawContext` for widgets when you add them to panels, and for background painters when you add them to widgets.

**Comment by legoraft** [comment]
My file is called `WAdvancementWidget`, which can be called directly as `rootpanel.add(WAdvancementWidget)` right? I'll try the other solution asap

**Comment by legoraft** [comment]
> If you need a DrawContext you can implements the BackgroundPainter interface and draw what you want:
> 
> ```java
>         BackgroundPainter backgroundPainter = ((context, left, top, panel) -> {
>             //context means DrawContext
>             //left means x
>             //top means y
>             //panel means your root panel or your widget
>             ScreenDrawing.texturedGuiRect(context, left, top, panel.getWidth(), panel.getHeight(), new Identifier("minecraft:texture/block/dirt.png"), 0xFFFFFFFF);
>         });
> ```
> 
> There is another way to implements BackgroundPainter, there is no difference
> 
> ```java
>         BackgroundPainter backgroundPainter = new BackgroundPainter() {
>             @Override
>             public void paintBackground(DrawContext context, int left, int top, WWidget panel) {
>                 //context means DrawContext
>                 //left means x
>                 //top means y
>                 //panel means your root panel or your widget
>                 ScreenDrawing.texturedGuiRect(context, left, top, panel.getWidth(), panel.getHeight(), new Identifier("minecraft:texture/block/dirt.png"), 0xFFFFFFFF);
>             }
>         };
> ```

How would I implement this within my file? I'm not that experienced with libgui yet, sorry.

**Comment by Juuxel** [comment]
You can use custom background painters like this:
```java
@Override
public void addPainters() {
    BackgroundPainter myPainter = (context, left, top, panel) -> {
        // the background painting code here
    };
    rootPanel.setBackgroundPainter(myPainter);
}
```
You essentially only need to
1. create a custom background painter with a lambda or anonymous class
2. and set it as the background painter of the panel you want to edit.

**Comment by legoraft** [comment]
Yes! Thanks a lot, I finally got it working
