### ISSUE TITLE
PropertyDelegates do not appear to work correctly

### ISSUE THREAD

**Issue by EzioisAwesome56** [CottonMC/LibGui#222]
**Describe the bug**
While trying to create a GUI following the guide on Property Delegates, the propertydelegate does not return  the expected data. adding a print statement to the code suggests it is running twice, once with the expected data, and another with just 0

**To Reproduce**
1. follow the wiki pages for adding a property delegate
2. examine the incorrect property presented to the user in the GUI

**Expected behavior** *Optional*
The GUI render thread gets the correct value from the property delegate

**Screenshots** *Optional*
![image](https://github.com/CottonMC/LibGui/assets/21185626/44959c66-e166-4f30-99f9-bf8aebdfad3f)
![image](https://github.com/CottonMC/LibGui/assets/21185626/ef85ebda-55e5-4b9a-8a9d-dd50c2375630)
![image](https://github.com/CottonMC/LibGui/assets/21185626/f4503763-1f74-4fc6-bf11-ac7ebdb80af0)
![image](https://github.com/CottonMC/LibGui/assets/21185626/479dd5a3-ecbe-4a13-a46c-558a387606a0)

**Version of the (please complete the following information):**
 - LibGui:9.0.0+1.20.2
 - Fabric API 0.90.4+1.20.2
 - Minecraft 1.20.2

**Additional context** *Optional*
There was not any working example code provided either, so this was entirely a shot in the dark of how im supposed to be using this. Otherwise, I have not been able to find any working examples with this library for using a PropertyDelegate

**Comment by Juuxel** [comment]
This is not a bug. Property delegates sync data dynamically, and syncing isn't available yet in the GUI description's constructor.

The `3` printed in the log is the value that is directly available on the server. A synced GUI description (and any screen handler) exists on both sides to sync the screen data.

Likewise, the `0` you see in the label/log is the default value used in the client-sided PropertyDelegate before it has received data from its server counterpart. To get the actual data, property delegates are meant to be queried continuously.

If your data is meant to change when the screen is open: You can keep using a property delegate, and you should use dynamic widgets such as WDynamicLabel or WBar, which read the data directly each time they render.

If your data will stay the same the entire time the GUI is open: Use Fabric API's [extended screen handlers](https://fabricmc.net/wiki/tutorial:extendedscreenhandler) to send over screen opening data. The data will be available immediately in your GUI constructor on both sides.

**Comment by EzioisAwesome56** [comment]
Thank for you the reply, and sorry for reporting it as a bug, the docs made it sound like it did not need to be checked over and over until it updated

as you suggested, i replaced the WLabel with a WDynamicLabel (+ a StringSupplier) and now it works as i wanted it to.
![image](https://github.com/CottonMC/LibGui/assets/21185626/9e0160f1-8737-45ad-9c27-1c65dd300c7a)

**Comment by Juuxel** [comment]
Good to hear that it's working. The wiki page should probably get some text about property delegates being dynamic too with a WDynamicLabel or WBar usage example.
