### ISSUE TITLE
Icons shouldn't be rendered if there's a stack on given slot

### ISSUE THREAD

**Issue by Luligabi1** [CottonMC/LibGui#224]
**Is your feature request related to a problem? Please describe.**
While attempting to replicate 1.20's `CyclingSlotIcon` (used on Smithing Tables), I noticed there's no code to check if the current WItemSlot is empty (neither on the icon render logic nor as a standalone method in `WItemSlot`), so the icon is rendering regardless of items inside with no way to check for it.

**Describe the solution you'd like**
- Add `isEmpty` to `WItemSlot`
- Check before rendering Icons
     - Alternatively, a `shouldRender` default method could be added to the `Icon` interface, allowing each implementation to choose however they see fit

**Describe alternatives you've considered**
This all could be circunvented with a hacky accessor to `WItemSlot`'s `peers`, but that's just plain ugly.

**Additional context**
![java_ag4wmF8Idp](https://github.com/CottonMC/LibGui/assets/33578169/a66cce35-6d68-454b-ac29-5682bf31c305)
(open on another tab)

**Comment by Juuxel** [comment]
This should probably be a toggle on the slot widget.

**Comment by Juuxel** [comment]
Duplicate of #203.
