### ISSUE TITLE
Backport server crash bugfix from latest release to versions compatible with 1.20.1

### ISSUE THREAD

**Issue by seeruk** [CottonMC/LibGui#234]
**Is your feature request related to a problem? Please describe.**
LibGui version 9.2.1 fixes an issue (#231), but is only compatible with versions of Minecraft from 1.20.2 onwards. At the moment, many mods have settled on 1.20.1 for this major version of Minecraft. This means any mod using LibGui (e.g. Automated Crafting, or the mod I'm also making) don't work on 1.20.1 (and in the case of Automated Crafting, they updated past 1.20.1 without the issue being fixed too).

**Describe the solution you'd like**
A backport of the fix to a version (e.g. a new 8.1.1 version) that is for 1.20.1.

**Describe alternatives you've considered**
I've already made a fork, built it, and am hosting it privately for my own use with my own mod, but it'd be great to not have to do this, and for other developers using LibGui to be able to make mods for the popular 1.20.1 version of Minecraft.

**Additional context**
N/A

**Comment by Luligabi1** [comment]
A single backport for 1.20.1 would be greatly appreciated - not only does this bug affect most if not all developers using this library, it'd also be great to use some of the new features on later releases.

> many mods have settled on 1.20.1 for this major version of Minecraft

Considering the release pattern of the last few years, 1.21 will release around early june, so it'd be 6 more months with this issue.

**Comment by Mysterious-Wrangler** [comment]
I would also appreciate these issues being fixed on 1.20.1

**Comment by MrMasrozYTLIVE** [comment]
I also would like if it was fixed

**Comment by Juuxel** [comment]
I backported the fix for the environment crashes to 1.20.1 as 8.1.1. If there are any other critical bugs that need to be fixed, I can also backport those later 👍
