### ISSUE TITLE
Incompatible With New Fabric Verision?

### ISSUE THREAD

**Issue by drkhodakarami** [CottonMC/LibGui#238]
Hi, these are the properties on my gradle : 

fabric_version=0.96.0+1.20.4
loader_version=0.15.6

When I try to run the client I get a popup window with incompatible version error:

Mod 'LibGui' (libgui) 9.2.2+1.20.2 reuires any version between 3.0.5 (inclusive) and 4- (exclusive) of mod 'Fabric Networking API (v1)' (fabric-networking-api-v1), but only the wrong version is present: 4.0.2+793274c962!

Mod 'LibGui' (libgui) 9.2.2+1.20.2 reuires any version between 3.0.5 (inclusive) and 4- (exclusive) of mod 'Fabric Rendering (v1)' (fabric-rendering-v1), but only the wrong version is present: 4.2.0+7e4ca3e162!

**Comment by Oiha-dev** [comment]
I have this issue too

**Comment by Juuxel** [comment]
Fixed in 10.0.0.

**Comment by voidpointer0x00** [comment]
@Juuxel this will not be backported to older versions? Would really appreciete 8.1.1 for 1.20.1
