### ISSUE TITLE
Add dynamic text objects (property labels, buttons, etc)

### ISSUE THREAD

**Issue by Fuyukai** [CottonMC/LibGui#24]
**Is your feature request related to a problem? Please describe.**
The default widgets all render fixed text, and need a subclass to achievee dynamic text labels.

**Describe the solution you'd like**
Having controls where the text on them is dynamic.

**Describe alternatives you've considered**
Subclassing to add these is possible, but it seems like something convenient enough to be included in the main library.

**Comment by Juuxel** [comment]
What do you mean by "dynamic"? The text of labels and buttons can be changed as of LibGui 1.4.0-beta.1.

**Comment by Fuyukai** [comment]
As in is automatically grabbed from the BE or whatever.

**Comment by Juuxel** [comment]
I've added dynamic labels that use `Supplier<String>` as the text in 12544fc.
