### ISSUE TITLE
Kotlin example for libgui

### ISSUE THREAD

**Issue by toastxc** [CottonMC/LibGui#241]
**Is your feature request related to a problem? Please describe.**
Is there an example in Kt for using this library? I'm trying it out and haven't managed to get it working yet.

**Describe the solution you'd like**
A simple and clean example of the Gui, that starts when a user enters a server.

**Describe alternatives you've considered**
For consistency the example *could* use an item, like the other examples.

**Additional context**
I'm fairly new to Minecraft dev (most of my time is spent in Rust), so I'm probably missing something obvious or silly.

**Comment by Juuxel** [comment]
There aren't any specific Kotlin examples for LibGui as the Java examples are equivalent and Minecraft modders should be able to at least read Java code. You can try using e.g. Idea's Java-to-Kotlin converter to translate the examples to Kotlin if needed.

If you have any specific questions, you can ask them here on Github or the Cotton discord.

**Comment by toastxc** [comment]
I understand, thank you.
