### ISSUE TITLE
update to mc 1.21

### ISSUE THREAD

**Issue by xxxkingxl** [CottonMC/LibGui#244]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Plz update to mc 1.21
**Describe alternatives you've considered**
none
**Additional context**
I like to update my modpack

**Comment by FreezePhoenix** [comment]
Which mods are you waiting on?

**Comment by xxxkingxl** [comment]
> Which mods are you waiting on?
I am waiting on command gui buttons (https://modrinth.com/mod/command-gui-buttons) requires LibGUI
And Music Player (https://www.curseforge.com/minecraft/mc-mods/music-player)

**Comment by Lilyp3892** [comment]
any updates? im also waiting on 1.21

**Comment by Juuxel** [comment]
The new update (11.0.0) supports 11.0.0. LibGui-wise, the update should be very painless for devs with minimal breaking changes. :smile:
