### ISSUE TITLE
WListPanel Rendering broken in 1.15

### ISSUE THREAD

**Issue by franiscoder** [CottonMC/LibGui#25]
**Describe the bug**
WListPanel rendering is broken in 1.15- I heard it was a z-problem. It normally appears that the text renders but anything else doesn't. 

**To Reproduce**
1. Make a test list panel.
2. Launch the game and test it out
3. if you did everything correctly it should show. 
**Screenshots** *Optional*
![2019-10-27_09 10 20](https://user-images.githubusercontent.com/45723631/71551262-14045580-29b1-11ea-97ba-ebd2ff10f420.png)
![2019-12-28_20 30 26](https://user-images.githubusercontent.com/45723631/71551263-14045580-29b1-11ea-829d-43c3dc0871b6.png)

![](https://cdn.discordapp.com/attachments/598330394118586403/655815795296960533/unknown.png)

**Version of the (please complete the following information):**
- LibGUI 1.4.0-beta.1
-my unreleased mod
 - Fabric API 0.4.25+build.282-1.15
 - Minecraft 1.15.1

**Comment by Juuxel** [comment]
Fixed in 661754ffb1e7150659d7dc43d3a7d024d776f0b5.
