### ISSUE TITLE
Unsure if this is CottonMC side or the actual mod, crash on opening a GUI releated to grid pannels

### ISSUE THREAD

**Issue by Gamercave** [CottonMC/LibGui#252]
**Describe the bug**
When right clicking a radio block from the mod: io.github.foundationgames.phonos a full server side crash occurs
**To Reproduce**
1. within create astral (v.2.1.1)
2. on a dedicated server
3. right click on a natrual spwaning radio block(may occur with a placed one unsure)
4. server crashes 

**Expected behavior** *Optional*
UI to open
**Screenshots** *Optional*

**Version of the (please complete the following information):**
 - io.github.foundationgames.phonos(0.3)
 - CottenMC
 - Fabric API
 - Minecraft

**Additional context** *Optional*
Add any other
Crash logs avalible
[crash-2024-10-21_09.50.24-server.txt](https://github.com/user-attachments/files/17458186/crash-2024-10-21_09.50.24-server.txt)
[crash-2024-10-21_09.53.00-server.txt](https://github.com/user-attachments/files/17458187/crash-2024-10-21_09.53.00-server.txt)
[crash-2024-10-21_07.25.27-server.txt](https://github.com/user-attachments/files/17458188/crash-2024-10-21_07.25.27-server.txt)
 context about the problem here.

**Comment by Juuxel** [comment]
1.18 is not supported. This bug (#231) has been fixed in LibGui 8.1.1 and newer. You can alternatively use Fabric Loader ≤0.14 as this crash only occurs on 0.15 or later versions.
