### ISSUE TITLE
Modify WListPanel.scrollBar.value programmatically

### ISSUE THREAD

**Issue by firegodjr** [CottonMC/LibGui#34]
**Problem**: I'd like to extend WListPanel to add onMouseScroll functionality, but when subclassing I cannot access this.scrollBar.value due to its protection level, and no methods exist to modify it.

Subclassing WClippedPanel and copy/pasting code from WListPanel is one way to circumvent this, but I feel as though it shouldn't be unnecessarily difficult to adjust a scrollbar programmatically.

**Comment by Juuxel** [comment]
I added `WScrollBar.setValue` (and some other missing getters and setters) in 5cab567.
