### ISSUE TITLE
Screen drawing issues on MacOS

### ISSUE THREAD

**Issue by LemmaEOF** [CottonMC/LibGui#46]
It seems that, on MacOS, the screen's height isn't properly set, resulting in things not being drawn properly. The zero position seems to be at the middle of the screen for button and widget rendering. I'm not super sure how to fix this.

![](https://cdn.discordapp.com/attachments/696494482698535052/697875609866731600/2020-04-09_11.27.44.png) ![](https://cdn.discordapp.com/attachments/696494482698535052/697875681547255850/2020-04-09_11.27.54.png)

**Comment by Boundarybreaker** [comment]
Looks like this is because of Retina displays sometimes calling themselves half the resolution they really are and sometimes calling themselves their *actual* resolution. The RetiNO mod fixes this issue, but I might look into PR'ing some hook to make it work better.
