### ISSUE TITLE
suggestion: move wiki to repo

### ISSUE THREAD

**Issue by fiws** [CottonMC/LibGui#58]
Imo it is better to have the documentation in the repo instead of a github wiki:

* Allows other to create PRs for the documentation
* Easily use branches for documentation (can also be a negative point as there can be outdated docs on older branches, but people usually only view the default branch anyway)
* Can update code & documentation in one go (eg. in one pull request)
* Sadly the wiki is enabled by default for new repos, so 90% of all github repos have this as a dead link. People tend to ignore it because of that.

Just a suggestion though. I could create a PR to migrate the wiki to the repo if wanted.

**Comment by Juuxel** [comment]
The github wiki is the most convenient option for me and it also stays separate from actual code in the repo. I won't be porting it over to any git repos.

**Comment by fiws** [comment]
oh.. ok. i wanted to contribute a few screenshots to the docs, as there are some missing. i guess there is no way to do that then?

**Comment by Juuxel** [comment]
You can ping me on Discord if you want me to add them :)
