### ISSUE TITLE
lang zh_cn.json

### ISSUE THREAD

**Issue by Lightcolour-666** [CottonMC/LibGui#6]
{
	"options.libgui.libgui_settings": "LibGui设置",
	"option.libgui.darkmode": "暗黑模式",
	"option.libgui.done": "完成"
}

**Comment by shedaniel** [comment]
Partition to use Minecraft’s own “Done” translation key so it will support like every translation

**Comment by Boundarybreaker** [comment]
Yeah, that should probably be MC's done translation

**Comment by falkreon** [comment]
Added, thanks for the translations! :)
