### ISSUE TITLE
Unable to include in project using gradle

### ISSUE THREAD

**Issue by fadookie** [CottonMC/LibGui#69]
**Describe the bug**
I've tried to follow the setup guide to install LibGui in my Fabric project but I'm unable to get Gradle to resolve the package.

Oddly enough it doesn't even look inside the maven repo:
```
A problem occurred configuring root project 'fabric-example-mod'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find any matches for io.github.cottonmc:LibGui:+ as no versions of io.github.cottonmc:LibGui are available.
     Searched in the following locations:
       - https://libraries.minecraft.net/io/github/cottonmc/LibGui/maven-metadata.xml
       - file:/Users/eliot/Dev/eliot/minecraft/fabric/fabric-example-mod/build/loom-cache/
       - file:/Users/eliot/Dev/eliot/minecraft/fabric/fabric-example-mod/.gradle/loom-cache/remapped_mods/
       - https://maven.fabricmc.net/io/github/cottonmc/LibGui/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/io/github/cottonmc/LibGui/maven-metadata.xml
       - https://jcenter.bintray.com/io/github/cottonmc/LibGui/maven-metadata.xml
       - file:/Users/eliot/.gradle/caches/fabric-loom/1.15.2-mapped-net.fabricmc.yarn-1.15.2+build.17-v2/
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

I've included my gradle files in this gist: https://gist.github.com/fadookie/00033db0de410675742acc760473a719

**To Reproduce**
If it's not obvious why this is happening and the supplied files aren't enough, let me know and I can try to construct an example repro case.

**Expected behavior** *Optional*
Package installs

**Screenshots** *Optional*
N/A

**Version of the (please complete the following information):**
 - Mod (Development Snapshot)
 - Fabric API 0.11.1+build.312-1.15
 - Minecraft 1.15.2

**Additional context** *Optional*

**Comment by Juuxel** [comment]
You need to add the Cotton maven repository in a top-level `repositories` block (for example above `dependencies`):

```groovy
repositories {
    maven {
        name = "Cotton"
        url = "https://server.bbkr.space/artifactory/libs-release/"
    }
}
```

**Comment by Juuxel** [comment]
I assume this is resolved? If not, just ask and I can reopen it.

**Comment by fadookie** [comment]
Thanks - I decided to go with Spinnery instead since I was able to get up and running with that first.

**Comment by Scrapmine** [comment]
I am having this verry issue with v8.0.2+1.20.

**Comment by Juuxel** [comment]
@Scrapmine
1. Check that you have declared the CottonMC maven repository in your build.gradle
2. Check that the dependency string and version are correct, for example without any leading `v` before the version (eg `io.github.cottonmc:LibGui:8.0.2+1.20`)
