### ISSUE TITLE
1.10.0 release does not appear to match sources

### ISSUE THREAD

**Issue by commandblockguy** [CottonMC/LibGui#70]
**Describe the bug**
The 1.10.0 release does not appear to match the sources.

**To Reproduce**
1. Download the release and jar from http://server.bbkr.space:8081/artifactory/libs-release/io/github/cottonmc/LibGui/1.10.0+1.15.2/
2. Alternatively, download the release from https://github.com/CottonMC/LibGui/releases/tag/1.10.0 and view the corresponding tag: https://github.com/CottonMC/LibGui/tree/1.10.0
3. See that some class files in the release, such as WScrollPanel and WVerticalBox, do not have corresponding java files in the sources

**Comment by Juuxel** [comment]
The tag is incorrect as it points to the 1.16 branch. The actual sources can be found from the `-sources` jar on the artifactory repository.

**Comment by commandblockguy** [comment]
The -sources jar on the artifactory repository also does not match the compiled jar.
