### ISSUE TITLE
Unable to close a screen using the inventory button after clicking on a slider

### ISSUE THREAD

**Issue by xxfast** [CottonMC/LibGui#82]
**Describe the bug**
Without clicking on a slider - a screen can be closed using `E` (inventory button). But after clicking on `E`, we are no longer able to close the screen.

**To Reproduce**
1. Open an example screen with a slider
2. Press `E` to confirm that you can close it
3. Open the screen once again and press on the slider
4. Unable to close the screen

**Expected behavior** 
Being able to close the screen with E even after clicking on the slider

**Version of the (please complete the following information):**
 - **Mod:** 3.0.0 - beta.1+1.16.2-rc2
 - **Fabric API** - 0.18.0+build.397-1.16
 - **Minecraft** - 1.16.2

**Comment by Juuxel** [comment]
This happens because the slider is focused when it's clicked. This cannot really be fixed as the slider needs the keyboard events for controlling it using the keyboard.
