### ISSUE TITLE
Is there a way to load image file from disk to WSprite?

### ISSUE THREAD

**Issue by Bloumbs** [CottonMC/LibGui#83]
Obviously its no problem if its images already in my assets folder, or some item in the game that already has an Identifier that I'm trying to use with `new WSprite(new Identifier("some identifier"))`, but I cant figure out how to (if its even possible) make an arbitrary path to an image `C:\Users\user\AppData\Roaming\.minecraft\... .png` usable as a WSprite.

Is there a way to convert some path of an image into an 'Identifier', or am I just to use the in-game item Identifiers or preloaded images etc in my assets? If its just the assets folder stuff, is it a thing to load external images into a mods assets folder or something?

_new to this stuff btw_

**Comment by Username404-59** [comment]
Are you trying to use textures of your mod, or of the base game?
Identifier works with two strings:
Identifier("yourmod", "textures/items/cheeseburger.png")
The second string is the path to your image inside the assets folder (from the first string, so by example if you write "minecraft" instead of "yourmod" it will search in the minecraft assets folder, else it will look into the assets folder of your mod).

**Comment by Boundarybreaker** [comment]
Any texture used in LibGui, or any other GUI system, needs to be inside of a loaded resource pack. This can be the vanilla resource pack, a mod resource pack, or a player-added resource pack. For security reasons, it can't just find any random file on your computer.

**Comment by Juuxel** [comment]
Boundary is correct about that -- it's an intentional MC limitation.

**Comment by Bloumbs** [comment]
@Boundarybreaker @Juuxel Oh okay. My intention was a users screenshots folder, which is what I meant by 'arbitrary path to image'.

**Comment by Username404-59** [comment]
> 
> 
> @Boundarybreaker @Juuxel Oh okay. My intention was a users screenshots folder, which is what I meant by 'arbitrary path to image'.

Well, i think it's totally possible as long as your mod create a folder inside .minecraft, and not outside of it..

**Comment by Bloumbs** [comment]
> > @Boundarybreaker @Juuxel Oh okay. My intention was a users screenshots folder, which is what I meant by 'arbitrary path to image'.
> 
> Well, i think it's totally possible as long as your mod create a folder inside .minecraft, and not outside of it..

Are you saying like copy images from their screenshot folder in .minecraft into the mods created folder, then ill have access with `Identifier("mymod", "assets/2020-08-31_04.23.46.png")` for a WSprite, or like if my mod creates a folder in .minecraft, ill have access to them with the normal `Identifier("minecraft", "screenshots/2020-08-31_04.23.46.png")`? I'm a little bit confused on how things go and how'd id use the `Identifier("id", "somefolder/filename.png")` thing.

**Comment by Boundarybreaker** [comment]
@Username404-59 It'd still not be doable. The resource pack system is *very* strict. There are a few hacky things you could do but LibGui WSprites aren't built for them. You'd need to likely make your own widget.
