### ISSUE TITLE
How to create an inventory GUI without an attached BlockEntity

### ISSUE THREAD

**Issue by coolnickname** [CottonMC/LibGui#89]
Like the title says. Something similar to the vanilla villager UI where you can move items from your inventory to the UI but the villager inventory doesn't store any items.

**Comment by Juuxel** [comment]
So, there are two main things you need to consider: opening the screen and the `GuiDescription` itself.

For the `GuiDescription`, your class should extend `SyncedGuiDescription` but doesn't need to provide any block inventory for the `super` constructor. If you don't have a `PropertyDelegate` either, you can just use the `(ScreenHandlerType, int, PlayerInventory)`.

As for the opening, you just have to create a `NamedScreenHandlerProvider` (can be an anonymous class, for example) and use `player.openHandledScreen(<your provider>)`.

**Comment by coolnickname** [comment]
Following the tutorial on the wiki, and implementing `NamedScreenHandlerFactory` in `ExampleBlockScreen` I still need to open the GUI. When trying to do
```player.openHandledScreen(new ExampleBlockScreen(new ExampleGuiDescription()));```
The ExampleGuiDescription constructor requires a syncId (int), PlayerInventory and ScreenHandlerContext.

I have a Player instance from which I can get the PlayerInventory, but I'm not sure what I should pass as syncId and how to get a ScreenHandlerContext. From the Player object I'm able to get a ScreenHandler and PlayerScreenHandler, but I don't know how to go about getting a ScreenHandlerContext instance.

**Comment by Juuxel** [comment]
The screen handler context parameter can really just be removed from your GUI description class (together with using the 3-parameter super class to `SyncedGuiDescription`), but you can also use `ScreenHandlerContext.EMPTY`.

**Comment by coolnickname** [comment]
Oh right, thanks. 
Right now it isn't crashing but the GUI is not showing up. I'm just passing `1` as the syncId and I guess that would be the cause, so what is a syncId and where can I generate one?

Also I noticed in order to create a `WItemSlot` I need an `Inventory` object. Is there any way around that and just to get the details from the itemslot in a callback?

**Comment by Juuxel** [comment]
The sync ID is just an internal value used when the game syncs screen data (such as items) between the server and the client. The game generates it for you. You should use `NamedScreenHandlerProvider` and construct your GUI description object in its `createMenu` method which has the sync ID as a parameter.

> Also I noticed in order to create a `WItemSlot` I need an `Inventory` object. Is there any way around that and just to get the details from the itemslot in a callback?

What do you mean by getting the details from the item slot? Note that you can create custom `Inventory` objects that don't depend on a block entity. For example, inventories can be backed by an item.

**Comment by Juuxel** [comment]
No response since October, so I'm closing this. Feel free to open another issue if you need more help.
