### ISSUE TITLE
Error when trying to open GUI by right clicking on a block

### ISSUE THREAD

**Issue by Arbee4ever** [CottonMC/LibGui#93]
I created an inventory gui using the libgui wiki. Eclipse doesnt show me any errors but when I try to open my gui I just get "Failed to create screen for menu type: vanillaaddons:backpack" What could cause this?

**Comment by Juuxel** [comment]
The error message means that you haven't registered a screen for your gui description/screen handler using `ScreenRegistry`. The wiki should have the correct code for registering one.

**Comment by Arbee4ever** [comment]
Thanks... I found out that It didnt run the client registry... I didnt know that I have to add it in the fabric.mod.json file... maybe add that to the Setup page?
