### ISSUE TITLE
Setting up LibGui, problem.

### ISSUE THREAD

**Issue by Dan7s** [CottonMC/LibGui#94]
I'm trying to Setup LibGui to my fabric mod project but i can't get it working. I followed the wiki tutorial, but even after that I can't manage to get it right. I'm using Eclipse IDLE and it's not even recognize

` import io.github.cottonmc.cotton.gui.GuiDescription; `

![image](https://user-images.githubusercontent.com/53444846/103538524-a11c9d00-4e96-11eb-98ba-ce1db84f8cf9.png)

Obviously doesn't work at all, so it's not just IDLE problem.

Part of  my `build.gradle`:
![image](https://user-images.githubusercontent.com/53444846/103538445-7df1ed80-4e96-11eb-8632-0876e215b7e6.png)

What am I doing it wrong or is it kind of bug?

**Comment by Dan7s** [comment]
EDIT:
I tried running it by the terminal, 
`./gradlew runClient`
works, so it might be problem with Eclipse. I tired `genEclipse` and `genEclipseRuns` but it doesn't changed anything. 

Running game with mod, by Eclipse returns:
`The method openScreen(Screen) in the type MinecraftClient is not applicable for the arguments (saveCordsScreen) The constructor saveCordsScreen(GuiDescription) refers to the missing type GuiDescription`

But running a game truth terminal works just fine:
![image](https://user-images.githubusercontent.com/53444846/103544124-e09bb700-4e9f-11eb-890f-10568fa9a4d4.png)

I suppose it's probably problem with Eclipse.

**Comment by Juuxel** [comment]
Yes, it seems to be an Eclipse issue. I'm not sure what causes it as I don't use Eclipse myself. Using another IDE, such as IDEA, might work better.

**Comment by TheKodeToad** [comment]
Right click on the project and press Gradle -> Refresh Gradle Project or something like that.
