### ISSUE TITLE
Tooltips are not working

### ISSUE THREAD

**Issue by tibetiroka** [CottonMC/LibGui#95]
**Describe the bug**
Added tooltips don't render on the widgets. Also the addTooltip(TooltipBuilder tooltip) method in WWidget is empty (and is not overridden in most widgets).
I thought it was removed due to some 1.16 issues, but there is no mention of it in the documentation nor in the commits.

**To Reproduce**
Use literally any widget with a tooltip. The tooltip will not render.

**Expected behavior**
The tooltips should render when the widget is hovered over.

**Version of the LibGUI:**
 - Mod version:  3.3.2+1.16.4 (latest)
 - Minecraft 1.16.4

**Comment by Juuxel** [comment]
Cannot reproduce. This might happen because the you have some other widget on top of the widget with tooltips (such as a label with no tooltip inside a panel with a tooltip).

> Also the addTooltip(TooltipBuilder tooltip) method in WWidget is empty (and is not overridden in most widgets).

This is intended, most widgets don't have tooltips.
