### ISSUE TITLE
How to get rid of background or make it invisible when using WTabPanel?

### ISSUE THREAD

**Issue by Dan7s** [CottonMC/LibGui#96]
So I'm trying to use `WTabPanel`, it works, but it always has a background. 

![image](https://user-images.githubusercontent.com/53444846/103693697-fd1c1a00-4f99-11eb-8825-4b3d5c2ddbbd.png)

Is it possible to make it similar to vanilla creative equipment menu?

**Comment by Juuxel** [comment]
You can override your GUI description's `addPainters` method to just do nothing, so the default background won't be set.
