### ISSUE TITLE
Ticking list from BiConsumer to reload content

### ISSUE THREAD

**Issue by Dan7s** [CottonMC/LibGui#97]
So I want to delete element from list on click on button. Every element has its own button to delete itself from list. It's working but i need to exit gui window or click on tab panel indicator or if i have enough elements, scroll to reload it. I know I can tick() list or Panel to reload its children, but i tried and it don't really work for me. How exactly and what I should tick() to make it working?

**Comment by Juuxel** [comment]
`tick` doesn't refresh children in stock LibGui widgets. You're most likely thinking of `layout`, which in `WListPanel` refreshes the list items when called. Try calling `layout` from your click handler after removing the element from the list.

**Comment by Dan7s** [comment]
Okay, now it's working perfectly. Thanks
