### ISSUE TITLE
Horizontal root box issue

### ISSUE THREAD

**Issue by PainDeMie64** [CottonMC/LibGui#98]
**Describe the bug**
So i made a box that is horizontal, and is the root of the gui. It opens fine, but all the things that I had to this horizontal box are in the top left corner. I tried multiple things, and everything is rendered in the same place, top left.

**To Reproduce**
1. Make a screen
2. Use a box (horizontal, vertical worked fine)
3. Add multiple widgets to it

**Version of the:**
 - all latest

**Comment by Juuxel** [comment]
Cannot reproduce with current master branch. (I suspect this is another labeled slider issue, and those will be fixed in 4.0).
